server:
    port: 9094
    servlet:
      context-path: /ratelimitercalls
      
resilience4j:
    ratelimiter:
        configs:
            default:
                limitForPeriod: 2
                limitRefreshPeriod: 1s
                timeoutDuration: 0
        instances:
            errorRateLimiterMonitor:
                baseConfig: default