server:
    port: 9095
    servlet:
      context-path: /retrycalls
      
resilience4j:
    retry:
        configs:
            default:
                maxAttempts: 3
                waitDuration: 100
                enableExponentialBackoff: true
                exponentialBackoffMultiplier: 2
                retryExceptions:
                    - org.springframework.web.client.HttpServerErrorException
        instances:
            testRetry:
                baseConfig: default
